spring:
  application:
    name: system-acceptance-tests

cucumber:
  legacy-backend: ${LEGACY_BACKEND_URL}

  users:
    admin:
      id: 1
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
    userA:
      id: 35568

  domains:
    sandbox1:
      id: 1
